#!/bin/sh

set -e

BINDIR="/usr/local/bin"
VIMDIR="/usr/local/vim"

list() {
  for v in ${VIMDIR}/${1:-*}.*; do
    [ -d ${v} ] && basename ${v}
  done | sort -n -t . -k 1,1 -k 2,2 -k 3,3
}

setup() {
  for l in ${BINDIR}/*; do
    [ -L ${l} ] && realpath ${l} | grep "^${VIMDIR}" >/dev/null && rm ${l}
  done

  for x in ${VIMDIR}/${1}/bin/*; do
    ln -s ${x} ${BINDIR}/$(basename ${x})
  done
  printf "\e[32;1mVim\e[0m %s\n" $(echo ${1} | sed -e 's/\.0*\([0-9]\+\)$/.\1/' -e 's/\.0$//')
}

case "${1}" in
7.4|8.[0-2]|9.[0-1])
  setup $(list ${1} | head -n 1)
  ;;
latest)
  setup $(list      | tail -n 1)
  ;;
esac
