#!/bin/sh

set -e

BINDIR="/usr/local/bin"
GODIR="/usr/local/go"

list() {
  if [ -n "${1}" -a -d ${GODIR}/"${1}" ]; then
    echo ${1}
  else
    for v in ${GODIR}/${1:-*}.*; do
      [ -d ${v} ] && basename ${v}
    done | sort -n -t . -k 1,1 -k 2,2 -k 3,3
  fi
}

setup() {
  for l in ${BINDIR}/*; do
    [ -L ${l} ] && realpath ${l} | grep "^${GODIR}" >/dev/null && rm ${l}
  done

  for x in ${GODIR}/${1}/bin/*; do
    ln -s ${x} ${BINDIR}/$(basename ${x})
  done
  go version
}

case "${1}" in
1.1[2-9])
  setup $(list ${1} | head -n 1)
  ;;
latest)
  setup $(list      | tail -n 1)
  ;;
esac
