name: Build
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        context:
          - go
          - python
          - vim
      fail-fast: false
    name: ${{ github.repository_owner }}/${{ matrix.context }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.dockerhub_token }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ github.repository_owner }}/${{ matrix.context }}:latest
          cache-to: type=inline
          context: ${{ matrix.context }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ github.repository_owner }}/${{ matrix.context }}:latest
